### ISSUE TITLE
List vs Array

### ISSUE THREAD

**Issue by pwrose** [rcsb/mmtf#10]
Should the word **list** be replaced by **array**, since the decoding generates arrays, not lists?

**Comment by arose** [comment]
My intention with using `list` instead or `array` was to have a more colloquial term that isn't as much associated with a specific 'type' in a programming language as the specific 'type' depends on the programming language and the the decoding library.

**Comment by pwrose** [comment]
See:
https://www.quora.com/What-is-the-difference-between-an-array-a-list-and-a-linked-list

On Thu, Jun 2, 2016 at 4:14 PM, Alexander Rose notifications@github.com
wrote:

> My intention with using list instead or array was to have a more
> colloquial term that isn't as much associated with a specific 'type' in a
> programming language as the specific 'type' depends on the programming
> language and the the decoding library.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> https://github.com/rcsb/mmtf/issues/10#issuecomment-223450149, or mute
> the thread
> https://github.com/notifications/unsubscribe/ADuwEApwenVHYeh2-97Ic4ml2_-JUPJLks5qH2PlgaJpZM4ItCzm
> .

## 

Peter Rose, Ph.D.
Site Head, RCSB Protein Data Bank West (http://www.rcsb.org)
San Diego Supercomputer Center (http://bioinformatics.sdsc.edu)
University of California, San Diego
+1-858-822-5497

**Comment by arose** [comment]
changed the wording in the spec use of "array" when describing fields of type Array, see 9395361b1495271eac5a0e74ddc5af00655bc8be
