### ISSUE TITLE
Bonds missing in NMR models after first

### ISSUE THREAD

**Issue by BobHanson** [rcsb/mmtf#15]
In 1cdr.mmtf we see for inter-group bonds from the main bondAtomList:

inter-group (1.1179/1.1166) bond ASN77.N - GLU76.C 1
inter-group (1.1194/1.250) bond NAG78.C1 - ASN18.ND2 1
inter-group (1.1220/1.1204) bond NAG79.C1 - NAG78.O4 1
inter-group (1.1248/1.1206) bond FUC80.C1 - NAG78.O6 1

where 1.1248 indicates this is for the first model. This is correct. Going to the second model, we see only:

inter-group (2.2448/2.2435) bond ASN77.N - GLU76.C 1
inter-group (3.2559/3.2540) bond GLN2.N - LEU1.C 1

The bonds are missing in the bondAtomList array:

[21, 2, 38, 23, 48, 40, ..., 2433, 2416, 2448, 2435, ??? ????, 2559, 2540, 2576, 2561, ...]

where we should see 2473, 2489, I believe. 

![Uploading toMMTF1.png…]()

Bob Hanson

**Comment by arose** [comment]
@BobHanson can you try uploading the image again, thank you.

**Comment by arose** [comment]
Good find, that originates from biojava. We need to fix that, thanks!

Model 0
![screenshot 9](https://cloud.githubusercontent.com/assets/272250/17535610/7e9ce4e8-5e44-11e6-835e-d362bd44f7e8.png)

Model 1
![screenshot 8](https://cloud.githubusercontent.com/assets/272250/17535611/7ea02a0e-5e44-11e6-9cb6-638c31605f80.png)
