### ISSUE TITLE
Make biological assemblies available

### ISSUE THREAD

**Issue by tomnewport** [rcsb/mmtf#27]
Can author/automatically assigned biological assemblies be made available? I am trying to access files like this one: https://files.rcsb.org/download/1U77.pdb1.gz via MMTF.

**Comment by esguerra** [comment]
You mean?

curl http://mmtf.rcsb.org/v1.0/full/1U77.mmtf.gz -o 1U77.mmtf.gz

**Comment by speleo3** [comment]
Tom, it's stored in [bioAssemblyList](https://github.com/rcsb/mmtf/blob/HEAD/spec.md#bioassemblylist)

**Comment by tomnewport** [comment]
Great! Many thanks :100:
