### ISSUE TITLE
assembly subunit ordering

### ISSUE THREAD

**Issue by speleo3** [rcsb/mmtf#30]
The ordering of assembly subunits seems to be different in MMTF and mmCIF files. This was reported on the pymol-users mailing list (https://sourceforge.net/p/pymol/mailman/message/36005513/).

I'm not aware that assembly ordering would be part of any spec, so technically there is nothing wrong here. But for consistency, it would be nice to provide identical assembly descriptions. In PyMOL, assemblies from mmCIF files are identical to pdb1 files, so I assume we're reading the mmCIF files correct.

Example: Assembly ordering for 3bw1:
mmCIF: 1 2 3 4
MMTF: 4 2 1 3

**Comment by josemduarte** [comment]
Good catch, thanks for reporting it! Indeed the spec doesn't (and shouldn't) constrain that. But I agree it would be nice to have consistency in the files provided by RCSB. We'll see if that can be fixed at some point.

**Comment by pwrose** [comment]
Refiled this issue: https://github.com/biojava/biojava/issues/770

**Comment by josemduarte** [comment]
This should be fixed now. We've regenerated all files after the fix for https://github.com/biojava/biojava/issues/770 by @pwrose

**Comment by speleo3** [comment]
Confirming that [3bw1](https://www.rcsb.org/structure/3bw1) MMTF and mmCIF load with identical ordering.
My PyMOL test:
```
set grid_mode
set assembly, 1
fetch 3bw1, mmcif, type=cif, async=0
fetch 3bw1, mmtf, type=mmtf, async=0
import psico.viewing
spectrum_states
```
