### ISSUE TITLE
inconsistent reduced representation of 5ijo

### ISSUE THREAD

**Issue by speleo3** [rcsb/mmtf#31]
The reduced model for 5ijo has numBonds=0, but len(bondOrderList)=2 and len(bondAtomList)=4.

```python
>>> import simplemmtf
>>> d = simplemmtf.from_url('http://mmtf.rcsb.org/v1.0/reduced/5ijo')
>>> d.get('numBonds')
0
>>> d.get('bondOrderList')
array('b', [1, 1])
>>> d.get('bondAtomList')
array('i', [2959, 1342, 7253, 1812])
```

Expected: len(bondOrderList)=0 and len(bondAtomList)=0
or numBonds=2 (though there should really be no bonds in a CA-only model)

**Comment by pwrose** [comment]
There are two covalent CA-CA bonds specified in the 5ijo.cif file. I'll file an issue with PDB to check these bond definitions.

covale1   covale none ? C PRO 173  CA ? ? ? 1_555 D ILE 1688 CA ? ? C PRO 173  D ILE 1688 1_555 ? ? ? ? ? ? ? 1.628 ? 
covale32  covale none ? C SER 680  CA ? ? ? 1_555 K ASP 853  CA ? ? C SER 680  K ASP 853  1_555 ? ? ? ? ? ? ? 1.591 ?

**Comment by speleo3** [comment]
Apparently this has been fixed, closing the case.
```python
>>> import simplemmtf
>>> d = simplemmtf.from_url('http://mmtf.rcsb.org/v1.0/reduced/5ijo')
>>> d.get('numBonds')
0
>>> 
>>> d.get('bondOrderList')
array('b')
>>> 
>>> d.get('bondAtomList')
array('i')
```
