### ISSUE TITLE
Generating a super cell from the mmtf.

### ISSUE THREAD

**Issue by jcminerlanl** [rcsb/mmtf#46]
Hello,

I am used to working with PDB structures, but I wanted to know if it was possible to generate a supercell (tessellated unit cells) from the mmtf file once it has been fetched?

**Comment by josemduarte** [comment]
The mmtf file has all the relevant crystallographic information needed to do that. If what you want is to visualize a supercell, then you might want to look at some examples with the NGL viewer.

I'd also recommend that you check out [BinaryCIF](https://github.com/molstar/BinaryCIF) and [Mol*](https://github.com/molstar/molstar/). BinaryCIF is the successor to MMTF.
