### ISSUE TITLE
'RCSB restricted area' for some PDB IDs

### ISSUE THREAD

**Issue by padix-key** [rcsb/mmtf#48]
For some PDB IDs, the access to the MMTF files is restricted: The server shows a 'RCSB restricted area' message and asks for username and password.

Examples:

`https://mmtf.rcsb.org/v1.0/full/1o1z`
`https://mmtf.rcsb.org/v1.0/full/4gxy
`

For `https://mmtf.rcsb.org/v1.0/full/1aki` and most other PDB IDs, the download works as expected.

**Update:**

This behavior seems inconsistent: At some attempts it works as expected, but some attempts later it shows the message again.

**Comment by samirelanduk** [comment]
I think this is related to a CORS error I am having when loading MMTF files from a web page. An hour or so ago the request was blocked by CORS, when @padix-key reported their error was fixed my web page was requesting correctly again, and now that @padix-key changed the outcome to 'inconsistent' the CORS error is back.

7M3K fails for example: [https://zincbind.net/pdbs/7M3K/](https://zincbind.net/pdbs/7M3K/). This is also locked in the way that @padix-key describes.

**Comment by josemduarte** [comment]
The problem should be solved now. Let us know if you see any other issues.

**Comment by paul-shannon** [comment]
Perhaps this problem has surfaced again?
```
STAGE LOG loading file '1IZL'
pheophytin.html:1 Access to XMLHttpRequest at 'http://mmtf.rcsb.org/v1.0/full/1IZL' from origin 'null' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
```

**Comment by josemduarte** [comment]
I do see the CORS header when I try one of the examples above:
```
$ curl -i https://mmtf.rcsb.org/v1.0/full/1o1z 
date: Mon, 06 Feb 2023 21:55:03 GMT
content-type: application/octet-stream
content-length: 20950
last-modified: Sat, 28 Jan 2023 04:35:48 GMT
etag: "63d4a624-51d6"
content-encoding: gzip
access-control-allow-origin: *
cache-control: max-age=3600
accept-ranges: bytes
strict-transport-security: max-age=16000000; includeSubDomains; preload;
x-backend-server: 10.100.6.25

```
