### ISSUE TITLE
why was mmtf dropped?

### ISSUE THREAD

**Issue by pgbarletta** [rcsb/mmtf#49]
I'd appreciate it if anyone would spare 5 mins. I'm training models on the PDB and I'd love a binary format alternative for these kinds of tasks

**Comment by gtauriello** [comment]
I can point to a few efforts for some binary formats for large scale analyses:

- [BinaryCIF](https://github.com/molstar/BinaryCIF) which is the successor of MMTF
- [Foldcomp](https://github.com/steineggerlab/foldcomp) as lossy and [PDC](https://github.com/kad-ecoli/pdc) as lossless/lossy formats to deal with the large AlphaFold DB (with limitations that would not allow you to handle everything in the PDB though)
- [ProteStAr](https://github.com/refresh-bio/protestar) and [OMF](https://openstructure.org/docs/io/io/#ost.io.ost.io.OMF) (heavily updated version coming up soon in release 2.6) also do lossless and lossy compression for large sets like the AlphaFold DB but are general enough to handle anything you find in the PDB

Also nothing stops you from using MMTF to convert PDB files into a binary format. Even though the tools around it are not being actively developed, I would assume that most of them still work fine.

**Comment by pgbarletta** [comment]
Thanks, hopefully one of these ends up being offered alongside PDBs, PDBxs.

**Comment by gtauriello** [comment]
BinaryCIF is offered alongside PDB and mmCIF (see e.g. [here](https://www.rcsb.org/docs/programmatic-access/file-download-services#pdb-entry-files))

**Comment by pgbarletta** [comment]
awesome, I had missed that!
Thanks again for taking the time.

**Comment by wojdyr** [comment]
There is also mmJSON (the content of mmCIF in JSON) available from PDBj.

**Comment by josemduarte** [comment]
One additional fresh data point is that as of the last PDB update this week, there's a structure [8ckb](https://www.rcsb.org/structure/8ckb) that broke the 4-character author chain id assumption in the mmtf spec. Note that the RCSB PDB still provides up-to-date mmtf files for the whole PDB archive, but will be discontinuing that feature in the near future (announcements will be made).

**Comment by wojdyr** [comment]
Perhaps it could be remediated? The mmCIF format is badly under-specified, so naming the chains mychain001 is formally correct, but it will cause problem in many programs.

**Comment by samirelanduk** [comment]
Just to confirm - MMTF has no future? I have a library which has MMTF as one of the four filetypes it parses and which is still actively developed - would it make sense to drop this and focus on the other three? (BinaryCIF is one of the other three.)

**Comment by josemduarte** [comment]
> Just to confirm - MMTF has no future? 

Correct. We recommend that the community moves to BinaryCIF as an efficient (whilst metadata-complete) file format. BinaryCIF is backed by the whole wwPDB. 

MMTF will continue to exist since the tools are still available (though only minimally maintained), but MMTF files for the PDB archive will soon not be produced anymore by RCSB PDB.

**Comment by wojdyr** [comment]
@samirelanduk IIUC you wrote both BinaryCIF and MMTF parsers. How do they compare in terms of complexity and speed?

**Comment by speleo3** [comment]
One really nice property of MMTF is that it explicitly stores all bonds, and does not depend on external dictionaries like the [Chemical Component Dictionary](https://www.wwpdb.org/data/ccd). Can BinaryCIF also provide that?

**Comment by arose** [comment]
> One really nice property of MMTF is that it explicitly stores all bonds, and does not depend on external dictionaries like the [Chemical Component Dictionary](https://www.wwpdb.org/data/ccd). Can BinaryCIF also provide that?

Yes, one has to include the chem_comp_bond categories in the BinaryCIF file. There appears to be some effort to do so in the PDB member provided files, see https://www.wwpdb.org/news/news?year=2023#649f0801d78e004e766a9680.

**Comment by speleo3** [comment]
> Yes, one has to include the chem_comp_bond categories in the BinaryCIF file. There appears to be some effort to do so in the PDB member provided files, see https://www.wwpdb.org/news/news?year=2023#649f0801d78e004e766a9680.

Thanks Alex. That sound like the "Updated mmCIF file" downloads provided by the PDBe. This helps a lot. It's still more complex than MMTF when you consider ALT locations, and you have to get the linkage right.

**Comment by pwrose** [comment]
One other difference between BinaryCIF and MMTF is that MMTF contains the
transformation matrices to create the biological assemblies. In CIF this is
not straightforward since the transformations are encoded for complex
assemblies, such as viruses. For example, for PDB 1M4X the transformation
matrices must be created from_pdbx_struct_assembly_gen.oper_expressions:
loop_
_pdbx_struct_assembly_gen.assembly_id
_pdbx_struct_assembly_gen.oper_expression
_pdbx_struct_assembly_gen.asym_id_list
1 '(1-60)(61-88)'           A,B,C
2 '(61-88)'                 A,B,C
3 '(1-5)(61-88)'            A,B,C
4 '(1,2,6,10,23,24)(61-88)' A,B,C
5 '(1-5)(63-68)'            A,B,C
6 '(1,10,23)(61,62,69-88)'  A,B,C
7 '(P)(61-88)'              A,B,C

**Comment by pwrose** [comment]
Another difference is how secondary structure is handled. CIF contains secondary structure that has been assigned by different algorithms over the past 5 decades. In contrast, MMTF contains consistently calculated DSSP secondary structure for all structures in the PDB.

**Comment by samirelanduk** [comment]
@wojdyr I've found BinaryCIF is much less complex to parse as once you've performed the decompressing you basically have the mmCIF ready to go, whereas with MMTF you then have to decompress and then perform the additional step of constructing the mmCIF tables you want from the MMTF dictionary. I haven't done a speed of parsing comparison, but I'd be surprised if it was a big difference.

**Comment by josemduarte** [comment]
An update: the MMTF-format files produced weekly for the entire PDB archive and served at mmtf.rcsb.org will be deprecated on the 2nd of July 2024. See the [announcement](https://www.rcsb.org/news/feature/65a1af31c76ca3abcc925d0c)

**Comment by wojdyr** [comment]
By the way, that structure that broke the four character chain name assumption, 8ckb, has been remediated in PDBe and I was told that the chain names will be limited to four characters now.

What's the rationale for replacing MMTF with BinaryCIF?

**Comment by josemduarte** [comment]
> 8ckb, has been remediated in PDBe and I was told that the chain names will be limited to four characters now.

Oh nice, I hadn't seen that. Thanks. The corresponding MMTF file should be out next week.

> What's the rationale for replacing MMTF with BinaryCIF?

The main reason is that BinaryCIF is metadata complete and fully compatible with the mmCIF dictionary. As such it is more future proof and offers more flexibility. Plus it is a much more appropriate format for transmitting the archival data. Much of what we learned from MMTF went into designing BinaryCIF, so it is an evolution of the format.

In any case, I am sure we will continue seeing many more developments in this topic, given the data deluge coming from AI-produced models. Some of the new developments were pointed by @gtauriello above.
