### ISSUE TITLE
Magic number?

### ISSUE THREAD

**Issue by timholy** [rcsb/mmtf#50]
The `spec.md` file does not say anything about a [magic number](https://en.wikipedia.org/wiki/File_format#Magic_number). This is a common practice in many domains, because you can't always trust that users will preserve file names and their extensions. Unix command line utilities like `file` make use of magic numbers to identify file types. Does MMTF have a magic number? If not, might one be considered in a future iteration of the format?

**Comment by josemduarte** [comment]
Thanks for the suggestion. To my knowledge MMTF doesn't have a magic number. 

Having said that I must point out that MMTF is in maintenance mode and that [in a few weeks from now](https://www.rcsb.org/news/feature/663129f765d8a8cacaf76f9f) the RCSB PDB organization will stop producing MMTF files for the whole PDB archive. We recommend transitioning to the [BinaryCIF format](https://github.com/molstar/BinaryCIF)

**Comment by pwrose** [comment]
mmtf files are in the MessagePack format (https://github.com/msgpack/msgpack),
which unfortunately doesn't have a magic number.

**Comment by timholy** [comment]
If this is deprecated, let's close this.
