### ISSUE TITLE
Consider adding all operators needed to construct full unitcell

### ISSUE THREAD

**Issue by arose** [rcsb/mmtf#6]

**Comment by josemduarte** [comment]
i.e. adding the space group operators table as in the symop.lib file from ccp4.

I'd vote against it, the format is about compression and this is redundant information that should come from elsewhere, e.g. a web service.

**Comment by arose** [comment]
playing opposition: the format is also about usefulness

**Comment by sbliven** [comment]
BioJava is able to calculate these quite easily:

`SpaceGroup.parseSpaceGroup(structuredatainterface.getSpaceGroup())`

So maybe we should follow that precedent and require downstream libraries to supply it. I would think that most mmtf clients, e.g. molecular viewers, would already have to supply this info if they want to generate unit cells from PDB or mmCIF files.

**Comment by arose** [comment]
I agree with leaving them out.
